Repository taurus-org/taurus, pull requests merged in 2018-07, with the labels that each got.

#698 ImageCounterDevice force process last image
  lib/taurus/core/tango/img/img.py
Labels: enhancement

#769 Deprecate setUseParentModel(True)
  CHANGELOG.md
  doc/source/devel/examples/edit02.py
  doc/source/devel/examples/edit03.py
  doc/source/devel/examples/label04.py
  lib/taurus/qt/qtgui/base/taurusbase.py
  lib/taurus/qt/qtgui/button/taurusbutton.py
  lib/taurus/qt/qtgui/display/test/test_tauruslabel.py
  lib/taurus/qt/qtgui/panel/taurusform.py
  lib/taurus/qt/qtgui/panel/taurusmodelchooser.py
  lib/taurus/qt/qtgui/panel/taurusvalue.py
  lib/taurus/qt/qtgui/plot/taurusplot.py
Labels: enhancement

#758 Fix #757 (ReferenceError in TangoAttrValue)
  lib/taurus/core/tango/tangoattribute.py
Labels: bug

#775 Add a explicit replot when showing a trend
  lib/taurus/qt/qtgui/plot/taurustrend.py
Labels: bug

#766 Document TaurusValueLineEdit
  lib/taurus/qt/qtgui/input/tauruslineedit.py
Labels: enhancement

#697 Convert model name list to CaselessList
  lib/taurus/qt/qtgui/plot/taurustrend.py
Labels: bug

#767 Fix 647: simplify API for setting Formatter on forms
  lib/taurus/qt/qtgui/panel/taurusform.py
  lib/taurus/qt/qtgui/panel/taurusvalue.py
Labels: enhancement

#777 Allow travis to fail on builds for debian 8
  .travis.yml
Labels: bug

#776 Define correct focus on a 'apply' button
  lib/taurus/qt/qtgui/plot/qwtdialog.py
Labels: enhancement

#764 [TEP15] Implement TEP15 (support slices in fragments)
  doc/source/tep/TEP15.md
  lib/taurus/core/taurusmodel.py
  lib/taurus/qt/qtgui/display/test/test_tauruslabel.py
Labels: TEP-Candidate, enhancement

#782 Skip the console dir in TaurusWidgetFactory
  lib/taurus/qt/qtgui/util/tauruswidgetfactory.py
Labels: bug

#781 Make "Change Tango Host" action invisible
  CHANGELOG.md
  lib/taurus/qt/qtgui/container/taurusmainwindow.py
Labels: enhancement

#780 Fix #668 (case issue in TaurusForm.chooseModels)
  lib/taurus/qt/qtgui/panel/taurusform.py
Labels: bug
