Repository taurus-org/taurus, pull requests merged in 2018-02, with the labels that each got.

#646 Fix: Taurusform does not allow to change the label
  lib/taurus/qt/qtgui/display/tauruslabel.py
  lib/taurus/qt/qtgui/panel/taurusvalue.py
Labels: bug

#683 Fix false successes in travis unittests
  .travis.yml
Labels: bug, unittest

#674 Fix several issues in TaurusValueLineEdit
  lib/taurus/core/tango/tangoattribute.py
  lib/taurus/qt/qtgui/base/tauruscontroller.py
  lib/taurus/qt/qtgui/input/tauruslineedit.py
  lib/taurus/qt/qtgui/panel/taurusvalue.py
Labels: bug

#681 Proposing fix for issue #648 (taurusLabel.setModelIndex() not working).
  lib/taurus/qt/qtgui/base/taurusbase.py
  lib/taurus/qt/qtgui/base/tauruscontroller.py
  lib/taurus/qt/qtgui/display/demo/tauruslabeldemo.py
  lib/taurus/qt/qtgui/display/test/test_tauruslabel.py
Labels: bug

#684 Add mechanism to discover taurus.qt.qtgui plugins
  lib/taurus/qt/qtgui/__init__.py
Labels: enhancement

#691 Allow to remove log handlers from Logger
  CHANGELOG.md
  lib/taurus/core/util/log.py
Labels: enhancement

#693 Add listedModels kwarg to modelChooserDlg
  lib/taurus/qt/qtgui/panel/taurusmodelchooser.py
Labels: enhancement

#695 Allow to remove log handlers from Logger
  lib/taurus/core/util/log.py
Labels: enhancement

#692 Re-open PR Fix circular references (Issue 511-512)
  lib/taurus/core/tango/tangoattribute.py
  lib/taurus/core/taurusmodel.py
  lib/taurus/core/tauruspollingtimer.py
  lib/taurus/core/util/event.py
Labels: bug

#705 Add __name__ attribute in _BoundMethodWeakrefWithCall class
  lib/taurus/core/util/event.py
Labels: bug

#704 Import PyTango for Tango centric functions
  lib/taurus/qt/qtgui/panel/taurusmessagepanel.py
Labels: bug

#713 Release Jan18 support 3.x
  doc/man/tau2taurus.1
  doc/man/taurusconfigbrowser.1
  doc/man/tauruscurve.1
  doc/man/taurusdemo.1
  doc/man/taurusdesigner.1
  doc/man/taurusdevicepanel.1
  doc/man/taurusdoc.1
  doc/man/taurusform.1
  doc/man/taurusgui.1
  doc/man/taurusimage.1
  doc/man/tauruspanel.1
  doc/man/taurusplot.1
  doc/man/taurusremotelogmonitor.1
  doc/man/taurustrend.1
  doc/man/taurustrend1d.1
  doc/man/taurustrend2d.1
  doc/man/taurusui.1
  doc/man/taurusuic4.1
  lib/taurus/core/release.py
Labels: support-3.x
