Repository taurus-org/taurus, pull requests merged in 2019-11, with the labels that each got.

#1029 Adapt synoptic items to use current scene API
  lib/taurus/qt/qtgui/graphic/jdraw/jdraw_view.py
  lib/taurus/qt/qtgui/graphic/taurusgraphic.py
Labels: bug

#1030 Fix doSomething signal calls
  lib/taurus/qt/qtcore/util/emitter.py
Labels: bug

#1027 Fix #909: expose more modules from qwt5 in qtgui.plot
  lib/taurus/qt/qtgui/plot/__init__.py
Labels: PyQt4, bug, py2

#1032 Fix TaurusValueComboBox does not show set value
  lib/taurus/qt/qtgui/input/tauruscombobox.py
  lib/taurus/qt/qtgui/input/test/__init__.py
  lib/taurus/qt/qtgui/input/test/test_tauruscombobox.py
Labels: bug

#1024 Fix TaurusImageDialog.setModel Qt slot in py2
  lib/taurus/qt/qtgui/extra_guiqwt/plot.py
Labels: bug, py2
