Repository taurus-org/taurus, pull requests merged in 2019-03, with the labels that each got.

#876 Remove _{un,}subscribeEvents API in TaurusAttribute
  CHANGELOG.md
  lib/taurus/core/epics/epicsattribute.py
  lib/taurus/core/evaluation/evalattribute.py
  lib/taurus/core/tango/tangoattribute.py
  lib/taurus/core/taurusattribute.py
Labels: enhancement

#879 Avoid relative import error in jdraw module
  lib/taurus/qt/qtgui/graphic/jdraw/jdraw.py
  lib/taurus/qt/qtgui/graphic/jdraw/jdraw_view.py
Labels: bug

#885 Fix #884: exception in TaurusForm about QIcon pickle
  lib/taurus/qt/qtgui/panel/taurusmodellist.py
Labels: bug, py3

#889 Change log level in taurus.qt.qtgui entry point loading
  lib/taurus/qt/qtgui/__init__.py
Labels: enhancement

#890 Use PY_OBJECT for signal signatures
  lib/taurus/external/qt/compat.py
  lib/taurus/qt/qtcore/communication/communication.py
  lib/taurus/qt/qtgui/button/taurusbutton.py
  lib/taurus/qt/qtgui/graphic/taurusgraphic.py
  lib/taurus/qt/qtgui/model/qbasemodel.py
  lib/taurus/qt/qtgui/qwt5/curvesAppearanceChooserDlg.py
Labels: bug

#887 Add python version to PyQt info log
  lib/taurus/external/qt/__init__.py
Labels: enhancement

#877 (doc) Add note in the taurus coding conventions about Qt imports
  doc/source/devel/coding_guide.rst
Labels: enhancement

#886 Fix bytes/str issues in dropMimeData methods
  lib/taurus/qt/qtgui/extra_guiqwt/curvesmodel.py
  lib/taurus/qt/qtgui/panel/taurusmodellist.py
  lib/taurus/qt/qtgui/qwt5/curveprops.py
Labels: bug, py3

#896 Add unit to taurus.core `__init__.py`
  lib/taurus/core/init_bkcomp.py
  lib/taurus/core/units.py
Labels: bug
