Repository taurus-org/taurus, pull requests merged in 2019-07, with the labels that each got.

#921 Taurusgui config
  CHANGELOG.md
  lib/taurus/qt/qtgui/container/taurusmainwindow.py
  lib/taurus/qt/qtgui/taurusgui/taurusgui.py
Labels: enhancement

#935 Fix template for generated taurus guis
  CHANGELOG.md
  lib/taurus/qt/qtgui/taurusgui/res/init.template
  lib/taurus/qt/qtgui/taurusgui/res/setup.template
Labels: bug

#934 Accept unknown kwargs in taurus mixin class constructors
  lib/taurus/qt/qtcore/configuration/configuration.py
  lib/taurus/qt/qtgui/base/taurusbase.py
Labels: enhancement

#925 Update tests in travis (due to debian buster release)
  .travis.yml
Labels: enhancement, tests

#939 Change TaurusDevPanel inherited class
  lib/taurus/qt/qtgui/panel/taurusdevicepanel.py
  lib/taurus/qt/qtgui/taurusgui/__init__.py
Labels: enhancement

#948 Remove redundant import
  lib/taurus/qt/qtgui/panel/taurusdevicepanel.py
Labels: bug

#946 Relax TaurusDevPanel state checking
  lib/taurus/qt/qtgui/panel/taurusdevicepanel.py
  lib/taurus/qt/qtgui/panel/taurusform.py
Labels: bug

#950 Allow to open file in Windows
  lib/taurus/qt/qtgui/panel/taurusconfigeditor.py
Labels: bug

#954 Fix imports of QtWebkit
  lib/taurus/external/qt/QtWebKit.py
Labels: bug

#956 Improve TaurusLabelTest2 to support various pint versions
  lib/taurus/qt/qtgui/display/test/test_tauruslabel.py
Labels: bug, tests

#941 Document missing modules
  doc/source/conf.py
  doc/source/numpy.inv
  lib/taurus/core/resource/resvalidator.py
  lib/taurus/core/util/console.py
  lib/taurus/core/util/constant.py
  lib/taurus/core/util/decorator/__init__.py
  lib/taurus/core/util/decorator/decorator.py
  lib/taurus/core/util/decorator/typecheck.py
  lib/taurus/core/util/event.py
  lib/taurus/core/util/parse_args.py
  lib/taurus/core/util/property_parser.py
  lib/taurus/core/util/tablepprint.py
  lib/taurus/qt/qtcore/taurusqlistener.py
  lib/taurus/qt/qtcore/util/__init__.py
  lib/taurus/qt/qtcore/util/emitter.py
  lib/taurus/qt/qtcore/util/properties.py
  lib/taurus/qt/qtcore/util/signal.py
  lib/taurus/qt/qtdesigner/containerplugin.py
  lib/taurus/qt/qtdesigner/tauruspluginplugin.py
  lib/taurus/qt/qtgui/base/taurusbase.py
  lib/taurus/qt/qtgui/extra_guiqwt/curve.py
  lib/taurus/qt/qtgui/extra_guiqwt/image.py
  lib/taurus/qt/qtgui/qwt5/taurusplot.py
  lib/taurus/test/moduleexplorer.py
  lib/taurus/test/test_import.py
Labels: bug

#955 Fix launch taurus designer on windows (closes #871)
  lib/taurus/qt/qtdesigner/taurusdesigner.py
  lib/taurus/tauruscustomsettings.py
Labels: bug

#951 Use encoding in etree.tostring
  lib/taurus/qt/qtgui/taurusgui/taurusgui.py
  lib/taurus/qt/qtgui/taurusgui/utils.py
Labels: bug

#957 Fix config editor broken in #950
  lib/taurus/qt/qtgui/panel/taurusconfigeditor.py
Labels: bug

#958 Fix issue when setting compact mode before model
  lib/taurus/qt/qtgui/panel/taurusvalue.py
Labels: bug

#832 Qwheeledit hide of edition widget and returnPressed forwarding
  lib/taurus/qt/qtgui/input/qwheel.py
Labels: enhancement

#960 Remove utf8 encodeing in JSONCodec
  lib/taurus/core/util/codecs.py
  lib/taurus/core/util/test/test_codecs.py
Labels: bug, enhancement
