Repository taurus-org/taurus, pull requests merged in 2019-09, with the labels that each got.

#998 Avoid resolving dns aliases in tangohost fqdn expansion
  lib/taurus/core/tango/tangodatabase.py
  lib/taurus/core/tango/tangovalidator.py
  lib/taurus/core/tango/test/test_tangovalidator.py
  lib/taurus/core/util/fqdn.py
Labels: bug

#994 Refactor the test CI: use tox, pytest and tango-cs-docker
  .gitignore
  .travis.yml
  ci/tango_docker-compose.yml
  lib/taurus/core/epics/test/test_epicsattribute.py
  lib/taurus/core/util/test/test_timer.py
  lib/taurus/qt/qtgui/panel/taurusvalue.py
  lib/taurus/qt/qtgui/panel/test/test_taurusvalue.py
  lib/taurus/test/test_import.py
  tox.ini
Labels: enhancement, tests

#1005 Fix jdraw_view to work with JD element names with "/" but not being Tango
  lib/taurus/qt/qtgui/graphic/taurusgraphic.py
Labels: bug

#1008 Fix exception in TaurusModelChooser.getListedModels()
  lib/taurus/qt/qtgui/panel/taurusmodelchooser.py
Labels: bug, py3
