Repository taurus-org/taurus, pull requests merged in 2019-06, with the labels that each got.

#926 Fix #843: exception in taurusgui --new-gui with Py3
  lib/taurus/qt/qtgui/taurusgui/appsettingswizard.py
  lib/taurus/qt/qtgui/taurusgui/res/init.template
  lib/taurus/qt/qtgui/taurusgui/res/setup.template
Labels: bug, py3

#931 Add protection in _updateValidator
  lib/taurus/qt/qtgui/input/tauruslineedit.py
Labels: bug

#932 Add support to RGB24 encoding
  lib/taurus/core/util/codecs.py
Labels: enhancement

#936 Emit signal using new style
  lib/taurus/qt/qtgui/panel/taurusmodellist.py
Labels: enhancement
