Repository taurus-org/taurus, pull requests merged in 2019-02, with the labels that each got.

#857 Avoid infinite recursion in TangoDevice.__getattr__
  lib/taurus/core/tango/tangodevice.py
Labels: bug

#859 Avoid use of parent model in TaurusDevPanel
  lib/taurus/qt/qtgui/panel/taurusdevicepanel.py
  lib/taurus/qt/qtgui/panel/ui/TaurusDevPanel.ui
Labels: bug

#860 Avoid redundant display of units in TaurusForm (Fixes #642)
  lib/taurus/qt/qtgui/panel/taurusvalue.py
  lib/taurus/qt/qtgui/panel/test/test_taurusvalue.py
Labels: enhancement

#864 Release Jan19
  .bumpversion.cfg
  .travis.yml
  CHANGELOG.md
  doc/makeman
  doc/man/taurusconfigbrowser.1
  doc/man/tauruscurve.1
  doc/man/taurusdemo.1
  doc/man/taurusdesigner.1
  doc/man/taurusdevicepanel.1
  doc/man/taurusform.1
  doc/man/taurusgui.1
  doc/man/taurusiconcatalog.1
  doc/man/taurusimage.1
  doc/man/tauruspanel.1
  doc/man/taurusplot.1
  doc/man/taurustestsuite.1
  doc/man/taurustrend.1
  doc/man/taurustrend1d.1
  doc/man/taurustrend2d.1
  doc/source/index.rst
  doc/source/tep/index.rst
  doc/source/tep/res/tep0_workflow.png
  doc/source/tep/res/tep14_merge_Attr_and_Conf.png
  lib/taurus/core/epics/test/test_epicsattribute.py
  lib/taurus/core/evaluation/evalfactory.py
  lib/taurus/core/evaluation/test/test_evalattribute.py
  lib/taurus/core/release.py
  lib/taurus/core/resource/test/res/__init__.py
  lib/taurus/core/resource/test/res/attr_resources_file.py
  lib/taurus/core/resource/test/test_resfactory.py
  lib/taurus/core/resource/test/test_resvalidator.py
  lib/taurus/core/tango/tangoattribute.py
  lib/taurus/core/tango/tangodevice.py
  lib/taurus/core/tango/test/test_tangofactory.py
  lib/taurus/core/tango/util/formatter.py
  lib/taurus/core/taurusdevice.py
  lib/taurus/core/taurusmanager.py
  lib/taurus/external/qt/QtHelp.py
  lib/taurus/external/qt/compat.py
  lib/taurus/qt/qtgui/container/taurusmainwindow.py
  lib/taurus/qt/qtgui/graphic/taurusgraphic.py
  lib/taurus/qt/qtgui/input/qwheel.py
  lib/taurus/qt/qtgui/input/tauruslineedit.py
  lib/taurus/qt/qtgui/panel/qdataexportdialog.py
  lib/taurus/qt/qtgui/panel/taurusconfigurationpanel.py
  lib/taurus/qt/qtgui/panel/taurusdevicepanel.py
  lib/taurus/qt/qtgui/panel/taurusvalue.py
  lib/taurus/qt/qtgui/panel/test/test_taurusvalue.py
  lib/taurus/qt/qtgui/panel/ui/TaurusDevPanel.ui
  lib/taurus/qt/qtgui/plot/__init__.py
  lib/taurus/qt/qtgui/qwt5/curveprops.py
  lib/taurus/qt/qtgui/table/taurusdevicepropertytable.py
  lib/taurus/qt/qtgui/table/taurusvaluestable.py
  lib/taurus/qt/qtgui/taurusgui/conf/gui_noconf.py
  lib/taurus/qt/qtgui/taurusgui/conf/gui_selfconf.py
  lib/taurus/qt/qtgui/util/validator.py
  lib/taurus/tauruscustomsettings.py
Labels: tests

#869 Taurus model selector
  lib/taurus/qt/qtgui/panel/taurusmodelchooser.py
  setup.py
Labels: enhancement

#872 Fix TaurusModelSelector.__setTabItemModel method
  lib/taurus/qt/qtgui/panel/taurusmodelchooser.py
Labels: bug
