Repository taurus-org/taurus, pull requests merged in 2020-02, with the labels that each got.

#1056 (doc) Add plotting guide
  doc/source/devel/index.rst
  doc/source/devel/plotting_guide.rst
Labels: enhancement

#1049 Add debugging info on model handling exceptions
  CHANGELOG.md
  lib/taurus/qt/qtgui/panel/taurusform.py
Labels: enhancement

#1069 Avoid using --show-capture opt for pytest in py27-qt5
  tox.ini
Labels: bug

#1066 Make TaurusValue store third party subwidgets classID
  lib/taurus/qt/qtgui/panel/taurusvalue.py
Labels: enhancement

#1061 Avoid deadlock between push_event and poll
  .travis.yml
  lib/taurus/core/tango/tangoattribute.py
  lib/taurus/core/taurusfactory.py
Labels: bug

#1075 Fix py2qt5 tests (fixes #1073)
  .travis.yml
  CHANGELOG.md
  tox.ini
Labels: bug, tests

#1081 Allow to customize Worker for ThreadPool
  CHANGELOG.md
  lib/taurus/core/util/threadpool.py
Labels: enhancement

#1072 Avoid NoneType AttributeError
  lib/taurus/qt/qtgui/input/tauruslineedit.py
Labels: bug

#1058 Fix missing precision initialization
  lib/taurus/core/tango/tangoattribute.py
Labels: bug

#1039 Improve set formatter dialog
  CHANGELOG.md
  lib/taurus/qt/qtgui/base/taurusbase.py
  lib/taurus/tauruscustomsettings.py
  setup.py
Labels: enhancement

#1059 Improve v3->v4 migration API and docs
  CHANGELOG.md
  doc/source/devel/taurus3to4.rst
  lib/taurus/core/tango/tangodevice.py
Labels: bug, enhancement
